name: Update markdown files

on:
    # If you want it to run max once a day
    # schedule:
    # - cron: "25 8 * * *"    #runs at 12am PST each day


    # Allows for manual runs
    workflow_dispatch:


      # Runs on commit *if* there's been a new code file added
    # paths used to prevent self looping where the markdown
    # push is detected and triggers another git action
    push:
        branches:
            - main
        paths:
            - 'my-submissions/**'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout current repository content for latest
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

                  # Markdown generator is found in submodule
                  submodules: "true"
                  token: ${{ secrets.PAT }}

            - name: Setup python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - name: Install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r '.Readme Updater/requirements.txt'

            - name: Execute the markdown generation python script
              # -n: ignores previous .pkl stores of the modified dates (regenerate all from scratch)
              # -g: use github log history to determine creation and modification dates of files
              run: python '.Readme Updater/main.py' -n -g


              # Note: exit 0 should be redundant since this action triggers on a modification meaning
              #       at least one file edit, but might as well keep it in case of future changes
            - name: Commit updated markdown files to repo
              run: |
                  git config --global user.name "Zanger67/leetcode"
                  git config --global user.email "Zanger67[bot]@zanger67.github.io"
                  git add .
                  git commit -m 'Updated markdown files' || exit 0
                  git push
