name: '[Updating markdown files]'

on:
    # Allows for munual runs of workflow
    workflow_dispatch:

    # Default whenever a new code file is pushed to the main branch
    push:
        branches:
            - main
        paths:
            - 'my-submissions/**'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Call and run markdown generator
              uses: Zanger67/WikiLeet@main
              with:
                # Insert your LeetCode username here!
                username: Zanger