name: py

on:
  # schedule:
    # - cron: "25 8 * * *"    #runs at 12am PST each day
  
  push:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.PAT }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r '.Readme Updater/requirements.txt'

      - name: execute py script
        # run: python '.Readme Updater/main.py -n'
        # On pause for now since I need to rest so let's use the one that doesn't properly date everything
        # run: python '.Readme Updater/main.py' -n -g
        run: python '.Readme Updater/main.py' -n

      - name: commit to repo
        run: |
          git config --global user.name "Zanger67/leetcode"
          git config --global user.email "Zanger67[bot]@zanger67.github.io"
          git add .
          git commit -m 'Updated markdown files'
          git push
