name: py

on:
  schedule:
    - cron: "0 7 * * *"    #runs at 12am PST each day

permissions:
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r '.Readme Updater/requirements.txt'

      - name: execute py script
        run: python '.Readme Updater/main.py'

      - name: commit to repo
        run: |
          git add .
          git commit -m 'Update generated files'
          git push
